  version: "3"
  services:
    springBootApp:
      image: uday07/docker-postgres-springboot-demo:latest
      container_name: docker-postgres-springboot-demo-app
      environment:
        - POSTGRES_HOST=docker-postgres-springboot-demo-db
      ports:
        - "8081:8081"
      networks:
        - network
      depends_on:
        - db
      restart: on-failure

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db

    db:
      image: postgres:13.2
      container_name: docker-postgres-springboot-demo-db
      ports:
        - "5432:5432"
      networks:
        - network
      volumes:
        - volume:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=postgres

  networks:
    network:

  volumes:
    volume:


